[package]
name = "loop-rs"
version = "0.1.0"
authors = ["Rich Jones <miserlou@gmail.com>"]
description = "UNIX's missing loop command"

documentation = "https://github.com/Miserlou/Looper"
homepage = "https://github.com/Miserlou/Looper"
repository = "https://github.com/Miserlou/Looper"

readme = "README.md"
license = "MIT"

[dependencies]
clap = {version = "2.31", features = ["yaml"]}
subprocess = "0.1.12"
humantime = "1.1.1"

[[bin]]
name = "loop"
